Implement athanor project dependency
uts-cic/athanor-server pull request #41
Opened 2017-11-10 04:51 UTC by josephharfouch

In this change, we remove the athanor jar that ideally belongs to
the athanor project, and resolve a versioned distribution jar
that is automatically downloaded with the athanor project
which is now a dependency of this project. An athanor.jar
link in the athanor project directory points to the
versioned jar that we are dependent on my default.

2017-11-10 05:00 UTC, josephharfouch commented
Hi Andrew,
This branch changes are designed to work together with the dummy_sbt_project pull request which I just  submitted to the athanor project. 
If you like this project dependency scheme, I would have to test it again from the develop branch, and probably come in with few minor modifications (hopefully minor). It would be good if you have a chance to try it out as well, to make sure it is not working because of something on my local machine, as I have done  a lot of fiddling and trial and error to get this going. It would be great if it works smoothly as the athanor-server user does not have to do any more work, and we wouldn't have to put the athanor jar in athanor-server.  

**Please note** I am deleting the current athanor.jar which is currently supplied as part of the athanor-server/lib directory as part of this change so that this system can kick in. I guess we can go back to this copy if we need it as it would still be in git, but let me know if this is a problem. 

I also disabled the nlytx download from bintray for now so that I can finish this item. (See my comments in the code). I can enable it again as part of my following iteration if you have some ideas  on this. Let me know.

2017-11-10 06:26 UTC, andrewresearch requested changes
nlytx commons may not be needed to for this project now that some of that functionality moved to TAP. The reason it wasn't working was that it had the wrong resolver.

I think the potential problem with this approach is that anyone wanting to use athanor-server will need the athanor project as well.

I think better to publish the JAR to bintray.

2017-11-10 06:57 UTC, josephharfouch commented
Hi Andrew, Are you thinking of a user that will not be downloading the project via git? The athanor-server user will not be even aware of the athanor project dependency if I don't mention in the doc and if they don't see what build.sbt is doing, because it all happens behind the scenes via sbt. The only change I noticed is that it takes a little longer to do the initial download because sbt has to download two projects, and also it asks you to authenticate to github fist time during the first sbt compile in athanor-server which I didn't think is a problem. 

Never the less, I take your point the bintray scheme is simpler, althoug this scheme might provide more flexibility for the future. If you want me to go more the bintray way, do you want that to be automated and where about in bintray shall I publish the athanor jar? Also, how do you want me to proceed with this pull request. Is it ok if I just disable the scheme but leave the code in tact as I did with the other code to clone the file from git in case you change your mind in the future rather than delete the branch and loose the changes?

2017-11-11 05:16 UTC, andrewresearch commented
Not merging this in, as using bintray to pull in Athanor jar rather than depending on Athanor project.

2017-11-11 05:16 UTC, closed without merging